Subject: Intrusion Alert!!!
From: SImReD OS <SImReD_OS@example.com>
To: Administrator <admin@example.com>
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="===============1165924961=="

--===============1165924961==
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit

Intrusion Alert!!!

Check security of your os at computers at company!

--SImReD_OS

--===============1165924961==
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: 7bit
MIME-Version: 1.0

<html>
	<head></head>
	<body>
		<p>Intrusion Alert!!!</p>
		<p>Check security of your os at computers at company!</p>
		<img src="cid:150031231768.1145.15390206134399980357@kali" \>
	</body>
</html>

--===============1165924961==--
